const menuList=[
    {
        title:"首页",
        key:"/admin/home"
    },{
        title:"UI",
        key:"admin/ui",
        children:[
            {
                title:"按钮",
                key:"/admin/ui/button"
            },{
                title:"model",
                key:"/admin/ui/model"
            },{
                title:"loading",
                key:"/admin/ui/loading"
            },{
                title:"notice",
                key:"/admin/ui/notice"
            },{
                title:"message",
                key:"/admin/ui/message"
            },{
                title:"tabs",
                key:"/admin/ui/tabs"
            },{
                title:"tables",
                key:"/admin/ui/table"
            }
        ]
    },{
        title:"登陆",
        key:"/admin/login"
    },{
        title:"车辆管理",
        key:"/admin/city"
    },{
		title:"订单管理",
		key:"/admin/order",
	
		
	},{
		title:"权限管理",
		key:"/admin/permission"
	},{
		title:"图表列表",
		key:"/admin/echart",
		children:[
			{
				title:"柱形图",
				key:"/admin/echart/bar"
			},{
				title:"折线图",
				key:"/admin/echart/line"
			}
		]
	}
]

export default menuList