const menuList=[
    {
        title:"首页",
        key:"/admin/home"
    },{
        title:"UI",
        key:"admin/ui",
        children:[
            {
                title:"按钮",
                key:"/admin/ui/button"
            },{
                title:"model",
                key:"/admin/ui/model"
            },{
                title:"loading",
                key:"/admin/ui/loading"
            },{
                title:"notice",
                key:"/admin/ui/notice"
            },{
                title:"message",
                key:"/admin/ui/message"
            },{
                title:"tabs",
                key:"/admin/ui/tabs"
            },{
                title:"tables",
                key:"/admin/ui/table"
            }
        ]
    },{
        title:"登陆",
        key:"/admin/login"
    },{
        title:"车辆管理",
        key:"/admin/city"
    }
]

export default menuList